<template>
	<view class="container">
		<view class="start_page kenburns-top"></view>
		<view class="first-font">
			<text class="first-font-one">欢迎光临</text>
			<text class="first-font-two">欢迎来到未来的家...</text>
		</view>
		<button class="go-btn" @click="star">点击进入</button>
	</view>
</template>

<script>
	export default {
		data() {
			return {
			
			}
		},
		methods: {
			star() {
				uni.navigateTo({
					url: '/pages/home/home'
				});
			}
		}
	}
</script>

<style>
	.container {
		position: relative;
	}
	.first-font{
		position: fixed;
		z-index: 2;
		bottom: 35%;
		color: #FFFFFF;
		padding-left: 1rem;
	}
	.first-font-one {
		font-size: 1.6rem;
		display: block;
		margin-bottom: .5rem;
	}
	.first-font-two {
		font-size: .8rem;
		display: block;
	}
	.start_page {
		position: fixed;
		top: 0;
		bottom: 0;
		left: 0;
		right: 0;
		background: url('https://s1.ax1x.com/2020/08/05/asGW5t.png') 0 0 no-repeat;
	}
	.kenburns-top {
		-webkit-animation: kenburns-top 5s ease-out both;
		        animation: kenburns-top 5s ease-out both;
	}
	/* ----------------------------------------------
	 * Generated by Animista on 2020-5-28 22:51:37
	 * Licensed under FreeBSD License.
	 * See http://animista.net/license for more info. 
	 * w: http://animista.net, t: @cssanimista
	 * ---------------------------------------------- */
	
	/**
	 * ----------------------------------------
	 * animation kenburns-top
	 * ----------------------------------------
	 */
	@-webkit-keyframes kenburns-top {
	  0% {
	    -webkit-transform: scale(1) translateY(0);
	            transform: scale(1) translateY(0);
	    -webkit-transform-origin: 50% 16%;
	            transform-origin: 50% 16%;
	  }
	  100% {
	    -webkit-transform: scale(1.25) translateY(-15px);
	            transform: scale(1.25) translateY(-15px);
	    -webkit-transform-origin: top;
	            transform-origin: top;
	  }
	}
	@keyframes kenburns-top {
	  0% {
	    -webkit-transform: scale(1) translateY(0);
	            transform: scale(1) translateY(0);
	    -webkit-transform-origin: 50% 16%;
	            transform-origin: 50% 16%;
	  }
	  100% {
	    -webkit-transform: scale(1.25) translateY(-15px);
	            transform: scale(1.25) translateY(-15px);
	    -webkit-transform-origin: top;
	            transform-origin: top;
	  }
	}
	.go-btn {
		position: fixed;
		z-index: 2;
		bottom: 16%;
		left: 22%;
		width: 60%;
		border: .05rem solid #FFFFFF;
		color: #FFFFFF;
		text-align: center;
		line-height: 2.5rem;
		border-radius: 10rpx;
		background-color: transparent !important;
	}

</style>
